
package visao;

import dao.ProdutoDAO;
import javax.swing.table.DefaultTableModel;
import modelo.Produto;

/**
 * @author Arthur
 * Formulário para remover quantidade do estoque de um produto existente.
 * Esta classe representa a interface gráfica (JFrame) que permite ao usuário
 * visualizar os produtos cadastrados em uma tabela, selecionar um produto e
 * remover uma quantidade do seu estoque atual, atualizando a informação
 * no banco de dados.
 */
public class FrmRemoverEstoque extends javax.swing.JFrame {

    /**
     * Creates new form FrmRemoverEstoque
     */
    public FrmRemoverEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
/**
 * Carrega a tabela com todos os produtos cadastrados.
 * Busca os dados por meio do ProdutoDAO e popula a tabela gráfica.
 */
    
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        for (Produto produto : dao.getListaProdutos()) {
            String categoriaFormatada = produto.getCategoria().getNome()
                    + " - " + produto.getCategoria().getEmbalagem()
                    + " - " + produto.getCategoria().getTamanho();

            modelo.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getQuantidade(),
                produto.getMin(),
                produto.getMax(),
                categoriaFormatada
            });
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextRemove = new javax.swing.JTextField();
        jRemove = new javax.swing.JButton();
        jSairAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Estoque atual", "Estoque mínimo", "Estoque máximo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Adicionar ao estoque");

        jTextRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRemoveActionPerformed(evt);
            }
        });

        jRemove.setText("Remover");
        jRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveActionPerformed(evt);
            }
        });

        jSairAdd.setText("Sair");
        jSairAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextRemove)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSairAdd)
                    .addComponent(jRemove))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSairAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        if (this.jTable1.getSelectedRow() != -1) {
            String id = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString();
            String nome = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1).toString();
            String quantidadeAtual = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 2).toString();
            this.jLabel1.setText("Adicionar ao estoque de: " + nome + " (Atual: " + quantidadeAtual + ")");
        }
    }                                    

    private void jTextRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

 /**
 * Evento acionado ao clicar no botão "Remover Estoque".
 * Lê a quantidade informada, atualiza o produto e persiste a mudança.
 * Apresenta mensagens de sucesso ou erro conforme o caso.
 */
    private void jRemoveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            int linhaSelecionada = jTable1.getSelectedRow();
            if (linhaSelecionada == -1) {
                throw new Exception("Selecione um produto na tabela.");
            }

            String texto = jTextRemove.getText().trim();
            if (texto.isEmpty()) {
                throw new NumberFormatException();
            }

            int estoqueAtual = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 2).toString());
            int valorRemovido = Integer.parseInt(texto);
            int estoqueMinimo = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 3).toString());

            int novoEstoque = estoqueAtual - valorRemovido;

            if (novoEstoque < estoqueMinimo) {
                throw new Exception("Estoque não pode ser menor que o mínimo permitido (" + estoqueMinimo + ").");
            }

            jTable1.setValueAt(String.valueOf(novoEstoque), linhaSelecionada, 2);

            ProdutoDAO dao = new ProdutoDAO();
            Produto produto = dao.getListaProdutos().get(linhaSelecionada);
            produto.setQuantidade(novoEstoque);

            dao.atualizarProduto(produto);

            jTextRemove.setText("");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite um valor numérico válido.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }                                       

    private void jSairAddActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();        // TODO add your handling code here:
    }                                        

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        carregaTabela();
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRemoverEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRemoverEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRemoverEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRemoverEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRemoverEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRemove;
    private javax.swing.JButton jSairAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextRemove;
    // End of variables declaration                   
}
